import type { MediaItem } from "@/types";

export const universalPromotionsTV = {
  name: "Universal Promotions TV",
  url: "https://www.youtube.com/@universalpromotionsTV",
  channelId: "UC2KhbVy8dsDnWcReUojCqrA",
  uploadsPlaylistId: "UU2KhbVy8dsDnWcReUojCqrA",
  avatarUrl: "/media/universal/youtube/channel-avatar.jpg",
  facebookProfileImageUrl: "/media/universal/social/facebook-profile.jpg",
  joined: "2022-08-28",
  subscribers: "24.6K",
  videos: "763",
  views: "4,600,463",
  mission: {
    en: "We are dedicated to developing talent in boxing with one objective: creating world champions.",
    es: "Nos dedicamos a desarrollar talentos dentro de la disciplina del boxeo con un solo objetivo; crear campeones mundiales.",
  },
  links: {
    facebook: "https://www.facebook.com/profile.php?id=100046694032285",
    instagram: "https://www.instagram.com/universal_promotion_boxing/",
    tiktok: "https://www.tiktok.com/@universalpromotionstv",
  },
} as const;

export const instagramProfile = {
  name: "Universal Promotions P.R.",
  username: "universal_promotion_boxing",
  handle: "@universal_promotion_boxing",
  url: universalPromotionsTV.links.instagram,
  imageSrc: "/media/universal/instagram/profile.jpg",
  followers: "23.2K",
  following: "77",
  isVerified: true,
  category: "Sports Promoter",
  bio: "Nos dedicamos a desarrollar talentos dentro de la disciplina del boxeo con un solo objetivo; crear campeones mundiales.",
} as const;

export const instagramAssets = [
  {
    shortcode: "DZnhIj-hXIU",
    label: "Post",
    sourceUrl: "https://www.instagram.com/p/DZnhIj-hXIU/",
    imageSrc: "/media/universal/instagram/instagram-post-1.jpg",
    isVideo: false,
    metric: "Full fight",
    caption: "Bryan Perez vs Michael Castro from the Palacio de Recreacion y Deportes de Mayaguez.",
  },
  {
    shortcode: "DZnFdJUxeCR",
    label: "Post",
    sourceUrl: "https://www.instagram.com/p/DZnFdJUxeCR/",
    imageSrc: "/media/universal/instagram/instagram-post-2.jpg",
    isVideo: false,
    metric: "Full fight",
    caption: "Johniel Ramos vs Alex Pallette from the Palacio de Recreacion y Deportes de Mayaguez.",
  },
  {
    shortcode: "DZlgMiENj-R",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/DZlgMiENj-R/",
    imageSrc: "/media/universal/instagram/instagram-reel-1.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-1.mp4",
    isVideo: true,
    metric: "1.1K likes",
    caption: "Abraham \"The Hammer\" Perez wins the WBA interim flyweight title by split decision.",
  },
  {
    shortcode: "DZlcwp_N-8F",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/DZlcwp_N-8F/",
    imageSrc: "/media/universal/instagram/instagram-reel-2.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-2.mp4",
    isVideo: true,
    metric: "396 likes",
    caption: "Main event tension from the DAZN broadcast before the opening bell.",
  },
  {
    shortcode: "DZlbqyiNeCk",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/DZlbqyiNeCk/",
    imageSrc: "/media/universal/instagram/instagram-reel-3.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-3.mp4",
    isVideo: true,
    metric: "891 likes",
    caption: "Ringside action from the main event, framed for social-first highlight discovery.",
  },
  {
    shortcode: "DZlO-oBPU9j",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/DZlO-oBPU9j/",
    imageSrc: "/media/universal/instagram/instagram-reel-4.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-4.mp4",
    isVideo: true,
    metric: "323 likes",
    caption: "Caleb Tirado goes to war and earns a unanimous decision win.",
  },
  {
    shortcode: "DZlN8XNPbVM",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/DZlN8XNPbVM/",
    imageSrc: "/media/universal/instagram/instagram-reel-5.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-5.mp4",
    isVideo: true,
    metric: "1.6K likes",
    caption: "Caleb Tirado and Osmar Rodriguez close the first bout with a brawl.",
  },
  {
    shortcode: "DZlMP5rvI0-",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/DZlMP5rvI0-/",
    imageSrc: "/media/universal/instagram/instagram-reel-6.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-6.mp4",
    isVideo: true,
    metric: "312 likes",
    caption: "Caleb Tirado opens the DAZN main card with island heat.",
  },
  {
    shortcode: "CwqA6OFL353",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/CwqA6OFL353/",
    imageSrc: "/media/universal/instagram/instagram-reel-7.jpg",
    isVideo: true,
    metric: "Weigh-in",
    caption: "UP Boxing Series weigh-in content from the official Instagram archive.",
  },
  {
    shortcode: "CeWzuXmBV7l",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/CeWzuXmBV7l/",
    imageSrc: "/media/universal/instagram/instagram-reel-8.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-8.mp4",
    isVideo: true,
    metric: "Archive",
    caption: "Older fight-promo clip showing how far back the social media library goes.",
  },
  {
    shortcode: "CeMFsjCATUB",
    label: "Reel",
    sourceUrl: "https://www.instagram.com/p/CeMFsjCATUB/",
    imageSrc: "/media/universal/instagram/instagram-reel-9.jpg",
    videoSrc: "/media/universal/instagram/instagram-reel-9.mp4",
    isVideo: true,
    metric: "Archive",
    caption: "Event-promo reel from the Universal Promotions social archive.",
  },
] as const;

export const youtubeVideos = [
  {
    id: "Sx9Mex3rVwg",
    title: "Bryan Pérez vs Michael Castro | PELEA COMPLETA",
    duration: "22:08",
    kind: "Full fight",
    thumbnailSrc: "/media/universal/youtube/bryan-perez-vs-michael-castro.jpg",
  },
  {
    id: "b-_dnUmtXvs",
    title: "Johniel Ramos vs Alex Pallette | PELEA COMPLETA",
    duration: "23:44",
    kind: "Full fight",
    thumbnailSrc: "/media/universal/youtube/johniel-ramos-vs-alex-pallette.jpg",
  },
  {
    id: "jDliVFyne5M",
    title: "Giovan Meléndez vs Alejandro Bonilla | PELEA COMPLETA",
    duration: "16:34",
    kind: "Full fight",
    thumbnailSrc: "/media/universal/youtube/giovan-melendez-vs-alejandro-bonilla.jpg",
  },
  {
    id: "8RSS8mQYUE0",
    title: "Regresa JESSE RODRIGUEZ, BOMBA GONZÁLEZ a defender su campeonato | Noticias con el General",
    duration: "5:16",
    kind: "News",
    thumbnailSrc: "/media/universal/youtube/noticias-con-el-general.jpg",
  },
  {
    id: "cqMDr198DX8",
    title: "Análisis XANDER vs ENNIS, ROACH vs ZEPEDA, JULIO 11 PEDRÍN | UPinion Dividida",
    duration: "45:50",
    kind: "Podcast",
    thumbnailSrc: "/media/universal/youtube/upinion-xander-ennis-roach-zepeda.jpg",
  },
  {
    id: "QJeTESuxj4Q",
    title: "Conferencia de Prensa OFICIAL | CHOKE DE CAMPEONES",
    duration: "21:09",
    kind: "Press conference",
    thumbnailSrc: "/media/universal/youtube/choke-de-campeones-presser.jpg",
  },
  {
    id: "wFg3Hm0IP34",
    title: "TOP 5 LIBRA X LIBRA, ASHLEYANN LOZADA domina, Invitado Félix Caraballo | UPINION DIVIDIDA",
    duration: "50:35",
    kind: "Podcast",
    thumbnailSrc: "/media/universal/youtube/top-5-libra-ashleyann-lozada.jpg",
  },
  {
    id: "YCKps8e7iCY",
    title: "¿Cuál fue la mejor pelea entre Boricuas? Invitada STEPHANIE PIÑEIRO | UPinion Dividida",
    duration: "53:55",
    kind: "Podcast",
    thumbnailSrc: "/media/universal/youtube/stephanie-pineiro-upinion.jpg",
  },
] as const;

export const podcastConcepts = [
  {
    title: { en: "Fight-week preview", es: "Previa de semana de pelea" },
    description: {
      en: "A weekly preview that turns every card into searchable storylines, fighter angles, and sponsor inventory.",
      es: "Una previa semanal que convierte cada cartelera en historias buscables, ángulos de boxeadores e inventario para auspiciadores.",
    },
  },
  {
    title: { en: "Fighter table", es: "Mesa de boxeadores" },
    description: {
      en: "Long-form interviews with prospects, champions, trainers, and gym owners across the island.",
      es: "Entrevistas largas con prospectos, campeones, entrenadores y dueños de gimnasios de la isla.",
    },
  },
  {
    title: { en: "After the bell", es: "Después de la campana" },
    description: {
      en: "Post-fight reaction, highlight breakdowns, and clips packaged for YouTube, Shorts, Reels, and TikTok.",
      es: "Reacción post-pelea, análisis de highlights y clips empaquetados para YouTube, Shorts, Reels y TikTok.",
    },
  },
] as const;

/**
 * MEDIA CATALOG — public-source channel facts plus illustrative demo content.
 * Every item carries provenance (`source`, `sourceUrl`, `rightsStatus`, `isDemo`) and
 * connections (`relatedEventSlug`, `relatedFighterSlugs`), mirroring
 * BACKEND_MEDIA_CONTRACT.md so this can later swap to a real media API. Social/video
 * records are linked or cached as public-source thumbnails; no ownership is claimed.
 */
export const mediaItems: MediaItem[] = [
  /* ── Confirmed public channels ─────────────────────────────────────── */
  {
    slug: "universal-promotions-tv-channel",
    category: "highlight",
    format: "video",
    date: "2026-06-15",
    hue: 8,
    relatedFighterSlugs: [],
    source: "youtube",
    sourceUrl: universalPromotionsTV.url,
    rightsStatus: "embed_only",
    isDemo: false,
    title: {
      en: "Universal Promotions TV — official YouTube channel",
      es: "Universal Promotions TV — canal oficial de YouTube",
    },
    excerpt: {
      en: "The promotion's owned video channel already has 24.6K subscribers, 763 videos, and 4.6M+ views.",
      es: "El canal propio de video de la promotora ya cuenta con 24.6K suscriptores, 763 videos y más de 4.6M vistas.",
    },
  },
  {
    slug: "world-champion-mission",
    category: "interview",
    format: "video",
    date: "2026-06-15",
    hue: 44,
    source: "youtube",
    sourceUrl: universalPromotionsTV.url,
    rightsStatus: "public_reference",
    isDemo: false,
    title: {
      en: "Mission: develop talent and create world champions",
      es: "Misión: desarrollar talentos y crear campeones mundiales",
    },
    excerpt: {
      en: universalPromotionsTV.mission.en,
      es: universalPromotionsTV.mission.es,
    },
  },
  {
    slug: "podcast-growth-system",
    category: "podcast",
    format: "podcast",
    date: "2026-06-15",
    hue: 210,
    source: "podcast",
    sourceUrl: universalPromotionsTV.url,
    rightsStatus: "public_reference",
    isDemo: true,
    title: {
      en: "Podcast growth system for Puerto Rico boxing",
      es: "Sistema de crecimiento para el podcast del boxeo boricua",
    },
    excerpt: {
      en: "Episode pages, transcript SEO, fighter tags, sponsor slots, and short-form clips can turn the show into a year-round media asset.",
      es: "Páginas por episodio, SEO con transcripciones, tags por boxeador, espacios de auspicio y clips cortos pueden convertir el show en un activo de medios todo el año.",
    },
  },
  {
    slug: "bryan-perez-michael-castro-full-fight",
    category: "highlight",
    format: "video",
    date: "2026-06-15",
    hue: 12,
    runtime: youtubeVideos[0].duration,
    relatedFighterSlugs: ["bryan-perez"],
    source: "youtube",
    sourceUrl: `https://www.youtube.com/watch?v=${youtubeVideos[0].id}`,
    embedUrl: `https://www.youtube-nocookie.com/embed/${youtubeVideos[0].id}`,
    thumbnailUrl: youtubeVideos[0].thumbnailSrc,
    rightsStatus: "embed_only",
    isDemo: false,
    title: {
      en: youtubeVideos[0].title,
      es: youtubeVideos[0].title,
    },
    excerpt: {
      en: "A real full-fight asset from Universal Promotions TV, embedded as public YouTube content.",
      es: "Un activo real de pelea completa de Universal Promotions TV, integrado como contenido público de YouTube.",
    },
  },
  {
    slug: "johniel-ramos-alex-pallette-full-fight",
    category: "highlight",
    format: "video",
    date: "2026-06-15",
    hue: 36,
    runtime: youtubeVideos[1].duration,
    relatedFighterSlugs: ["johniel-ramos"],
    source: "youtube",
    sourceUrl: `https://www.youtube.com/watch?v=${youtubeVideos[1].id}`,
    embedUrl: `https://www.youtube-nocookie.com/embed/${youtubeVideos[1].id}`,
    thumbnailUrl: youtubeVideos[1].thumbnailSrc,
    rightsStatus: "embed_only",
    isDemo: false,
    title: {
      en: youtubeVideos[1].title,
      es: youtubeVideos[1].title,
    },
    excerpt: {
      en: "Full-fight video from the official channel, ready to connect to fighter and event archives.",
      es: "Video de pelea completa del canal oficial, listo para conectarse al archivo de boxeadores y eventos.",
    },
  },
  {
    slug: "upinion-dividida-xander-ennis-roach-zepeda",
    category: "podcast",
    format: "podcast",
    date: "2026-06-15",
    hue: 210,
    runtime: youtubeVideos[4].duration,
    source: "youtube",
    sourceUrl: `https://www.youtube.com/watch?v=${youtubeVideos[4].id}`,
    embedUrl: `https://www.youtube-nocookie.com/embed/${youtubeVideos[4].id}`,
    thumbnailUrl: youtubeVideos[4].thumbnailSrc,
    rightsStatus: "embed_only",
    isDemo: false,
    title: {
      en: youtubeVideos[4].title,
      es: youtubeVideos[4].title,
    },
    excerpt: {
      en: "UPinion Dividida proves the podcast/media lane is already active and can become a searchable sponsor product.",
      es: "UPinion Dividida prueba que el canal de podcast/medios ya está activo y puede convertirse en un producto auspiciable y buscable.",
    },
  },
  {
    slug: "choke-de-campeones-press-conference",
    category: "press-conference",
    format: "video",
    date: "2026-06-15",
    hue: 44,
    runtime: youtubeVideos[5].duration,
    source: "youtube",
    sourceUrl: `https://www.youtube.com/watch?v=${youtubeVideos[5].id}`,
    embedUrl: `https://www.youtube-nocookie.com/embed/${youtubeVideos[5].id}`,
    thumbnailUrl: youtubeVideos[5].thumbnailSrc,
    rightsStatus: "embed_only",
    isDemo: false,
    title: {
      en: youtubeVideos[5].title,
      es: youtubeVideos[5].title,
    },
    excerpt: {
      en: "A real press-conference video asset that belongs in the event/media archive instead of disappearing inside social feeds.",
      es: "Un video real de conferencia de prensa que debe vivir en el archivo de eventos y medios, no perderse dentro de redes sociales.",
    },
  },

  /* ── Build-up ──────────────────────────────────────────────────────── */
  {
    slug: "queen-of-the-ring-announced",
    category: "announcement",
    format: "article",
    date: "2026-06-10",
    hue: 210,
    relatedEventSlug: "queen-of-the-ring",
    relatedFighterSlugs: ["soledad-matthysse", "litzy-adilene-vazquez", "kiria-tapia"],
    source: "website",
    rightsStatus: "owned",
    isDemo: true,
    title: {
      en: "Universal Promotions sets Queen of the Ring for July 11",
      es: "Universal Promotions presenta Queen of the Ring el 11 de julio",
    },
    excerpt: {
      en: "Universal Promotions and Salita Promotions reunite for world championship boxing at Coliseíto Pedrín Zorrilla, with tickets through PRticket.com.",
      es: "Universal Promotions y Salita Promotions se unen nuevamente para boxeo de campeonato mundial en el Coliseíto Pedrín Zorrilla, con boletos por PRticket.com.",
    },
  },
  {
    slug: "rematch-set",
    category: "announcement",
    format: "article",
    date: "2026-06-02",
    hue: 320,
    relatedEventSlug: "noche-boricua",
    relatedFighterSlugs: ["noelia-figueroa", "keishla-marrero"],
    source: "website",
    rightsStatus: "owned",
    isDemo: true,
    title: {
      en: "Figueroa–Marrero rematch headlines Boricua Night",
      es: "La revancha Figueroa–Marrero encabeza Noche Boricua",
    },
    excerpt: {
      en: "After a razor-thin split decision in March, the island's two biggest stars run it back August 29.",
      es: "Tras una decisión dividida apretadísima en marzo, las dos grandes estrellas de la isla se ven las caras de nuevo el 29 de agosto.",
    },
  },
  {
    slug: "prospect-series-expands",
    category: "announcement",
    format: "article",
    date: "2026-04-18",
    hue: 150,
    relatedEventSlug: "ascenso",
    relatedFighterSlugs: ["yariel-quinones", "genesis-cordero"],
    source: "website",
    rightsStatus: "owned",
    isDemo: true,
    title: {
      en: "Universal expands its developmental Prospect Series",
      es: "Universal expande su serie de desarrollo de prospectos",
    },
    excerpt: {
      en: "A streaming-first platform for the island's next generation, with three more dates added.",
      es: "Una plataforma streaming-first para la próxima generación de la isla, con tres fechas adicionales.",
    },
  },
  {
    slug: "roots-presser",
    category: "press-conference",
    format: "gallery",
    date: "2026-05-06",
    hue: 36,
    itemCount: 28,
    relatedEventSlug: "raices",
    relatedFighterSlugs: ["andres-vazquez", "joel-nieves"],
    source: "manual",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Vázquez and Nieves trade words at the Roots kickoff presser",
      es: "Vázquez y Nieves se cruzan palabras en la conferencia de Raíces",
    },
    excerpt: {
      en: "Fight-week begins. Both lightweights stayed composed — until the staredown.",
      es: "Arranca la semana de pelea. Ambos ligeros se mantuvieron serenos — hasta el careo.",
    },
  },
  {
    slug: "roots-open-workout",
    category: "open-workout",
    format: "video",
    date: "2026-05-07",
    hue: 150,
    runtime: "4:36",
    relatedEventSlug: "raices",
    relatedFighterSlugs: ["bryan-otero"],
    source: "youtube",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Otero opens up for the Loíza faithful",
      es: "Otero abre los guantes para la afición de Loíza",
    },
    excerpt: {
      en: "The prospect ran the mitts in front of a hometown crowd ahead of Roots.",
      es: "El prospecto trabajó las manoplas ante su gente antes de Raíces.",
    },
  },
  {
    slug: "roots-weighin",
    category: "weigh-in",
    format: "gallery",
    date: "2026-05-09",
    hue: 28,
    itemCount: 24,
    relatedEventSlug: "raices",
    source: "manual",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Roots weigh-in: every fighter on the scale",
      es: "Pesaje de Raíces: cada boxeador en la balanza",
    },
    excerpt: {
      en: "All bouts official. Face-offs from the eve of fight night in San Juan.",
      es: "Todas las peleas oficiales. Careos en la víspera de la velada en San Juan.",
    },
  },
  {
    slug: "fury-faceoff",
    category: "faceoff",
    format: "gallery",
    date: "2026-03-20",
    hue: 300,
    itemCount: 12,
    relatedEventSlug: "furia-boricua",
    relatedFighterSlugs: ["noelia-figueroa", "keishla-marrero"],
    source: "manual",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Figueroa–Marrero faceoff turns electric",
      es: "El careo Figueroa–Marrero se enciende",
    },
    excerpt: {
      en: "The staredown that set the tone for a split-decision classic.",
      es: "El careo que marcó el tono de un clásico por decisión dividida.",
    },
  },

  /* ── Fight night ───────────────────────────────────────────────────── */
  {
    slug: "roots-gallery",
    category: "fight-night",
    format: "gallery",
    date: "2026-05-10",
    hue: 36,
    itemCount: 48,
    relatedEventSlug: "raices",
    source: "manual",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Roots — fight night in photos",
      es: "Raíces — la velada en fotos",
    },
    excerpt: {
      en: "Ringwalks, the main event, and a sold-out El Choliseo, shot ringside.",
      es: "Ringwalks, la pelea estelar y un Choliseo abarrotado, capturados a pie de ring.",
    },
  },
  {
    slug: "roots-result-main",
    category: "result",
    format: "article",
    date: "2026-05-11",
    hue: 44,
    relatedEventSlug: "raices",
    relatedFighterSlugs: ["andres-vazquez", "joel-nieves"],
    source: "website",
    rightsStatus: "owned",
    isDemo: true,
    title: {
      en: "Vázquez retains with a commanding decision over Nieves",
      es: "Vázquez retiene con una decisión contundente sobre Nieves",
    },
    excerpt: {
      en: "The champion controlled twelve rounds to keep his belt in front of a packed house.",
      es: "El campeón controló doce asaltos para retener su faja ante un coliseo lleno.",
    },
  },
  {
    slug: "roots-highlights-vazquez",
    category: "highlight",
    format: "video",
    date: "2026-05-11",
    hue: 44,
    runtime: "8:12",
    relatedEventSlug: "raices",
    relatedFighterSlugs: ["andres-vazquez"],
    source: "youtube",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Vázquez UD12 — round-by-round highlights",
      es: "Vázquez UD12 — resumen asalto por asalto",
    },
    excerpt: {
      en: "Every key exchange from the lightweight title defense at Roots.",
      es: "Cada intercambio clave de la defensa del título ligero en Raíces.",
    },
  },
  {
    slug: "roots-highlights-burgos",
    category: "highlight",
    format: "video",
    date: "2026-05-11",
    hue: 8,
    runtime: "1:45",
    relatedEventSlug: "raices",
    relatedFighterSlugs: ["damian-burgos"],
    source: "youtube",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Burgos KO4 — the finish",
      es: "Burgos KO4 — el desenlace",
    },
    excerpt: {
      en: "The biggest puncher on the roster ends it in the fourth.",
      es: "El de mayor pegada del roster lo acaba en el cuarto.",
    },
  },
  {
    slug: "origin-highlights-quinones",
    category: "highlight",
    format: "video",
    date: "2026-02-08",
    hue: 32,
    runtime: "2:03",
    relatedEventSlug: "origen",
    relatedFighterSlugs: ["yariel-quinones"],
    source: "youtube",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Quiñones KO2 — Origin",
      es: "Quiñones KO2 — Origen",
    },
    excerpt: {
      en: "Two rounds, one statement from the Ponce southpaw.",
      es: "Dos asaltos, una declaración del zurdo de Ponce.",
    },
  },

  /* ── Aftermath ─────────────────────────────────────────────────────── */
  {
    slug: "roots-recap",
    category: "recap",
    format: "article",
    date: "2026-05-12",
    hue: 36,
    relatedEventSlug: "raices",
    source: "website",
    rightsStatus: "owned",
    isDemo: true,
    title: {
      en: "Roots recap: a sold-out homecoming",
      es: "Recap de Raíces: un regreso a casa con todo agotado",
    },
    excerpt: {
      en: "Three finishes, a retained title, and the promotion's most-watched broadcast of the year so far.",
      es: "Tres nocauts, un título retenido y la transmisión más vista de la promotora en lo que va de año.",
    },
  },
  {
    slug: "marrero-interview",
    category: "interview",
    format: "video",
    date: "2026-06-05",
    hue: 198,
    runtime: "6:21",
    relatedEventSlug: "noche-boricua",
    relatedFighterSlugs: ["keishla-marrero"],
    source: "youtube",
    rightsStatus: "generated",
    isDemo: true,
    title: {
      en: "Five minutes with Keishla Marrero",
      es: "Cinco minutos con Keishla Marrero",
    },
    excerpt: {
      en: "The Bayamón southpaw on the rematch, the women's program, and carrying a card.",
      es: "La zurda de Bayamón sobre la revancha, el programa femenino y cargar una cartelera.",
    },
  },
  {
    slug: "otero-feature",
    category: "interview",
    format: "article",
    date: "2026-06-12",
    hue: 150,
    relatedFighterSlugs: ["bryan-otero"],
    source: "website",
    rightsStatus: "owned",
    isDemo: true,
    title: {
      en: "Bryan Otero on the weight of being ‘next’",
      es: "Bryan Otero y el peso de ser ‘el próximo’",
    },
    excerpt: {
      en: "The 22-year-old from Loíza on expectations, the co-main slot, and his hometown crowd.",
      es: "El joven de 22 años de Loíza sobre las expectativas, el coestelar y su afición.",
    },
  },
  {
    slug: "roots-sponsor-recap",
    category: "sponsor-recap",
    format: "article",
    date: "2026-05-14",
    hue: 44,
    relatedEventSlug: "raices",
    source: "website",
    rightsStatus: "owned",
    isDemo: true,
    title: {
      en: "Roots sponsor recap: 1.24M reached",
      es: "Recap de auspicio de Raíces: 1.24M de alcance",
    },
    excerpt: {
      en: "Placement-by-placement delivery for every partner on the card — see the sample report.",
      es: "Entrega ubicación por ubicación para cada socio de la cartelera — ver el reporte de muestra.",
    },
  },
];

const mediaBySlug = new Map(mediaItems.map((m) => [m.slug, m]));

export function getMediaItem(slug: string): MediaItem | undefined {
  return mediaBySlug.get(slug);
}
